conceptos = {
    "SERGIO SUAREZ CHECA": "transferencias interna",
    "SUAREZ CHECA SERGIO": "transferencias interna",
    "GRUPO NORDESTADA": "Deporte",
    "AOSSA GLOBAL": "Deporte",
    "OPENAI": "informática y otros",
    "LEGALITAS": "legalitas",
    "MIGUEL ANGEL SUAREZ LUNA": "regalo papis",
    "BOOKING": "vacaciones y reservas",
    "TRANSFERENCIA EMITIDA PERIÓDICA": "transferencias interna",
    "CUENTA NÓMINA MOVIMIENTO ING": "transferencias interna",
    "INTERESES A TU FAVOR": "Abono de intereses",
    "TRASPASO EMITIDO CUENTA NÓMINA MOVIMIENTO ING": "transferencias interna",
    "NÓMINA MOVIMIENTO  ING": "transferencias interna",
    "TRASPASO RECIBIDO CUENTA NÓMINA MOVIMIENTO ING": "transferencias interna",
    "GRUPO SUP AHORR": "alimentacion",
    "MERCADONA": "alimentacion",
    "DUXEL`S PELUQUE": "peluqueria",
    "ATRAPALO": "ropa",
    "LICEO EUROPEO": "colegio",
    "BALLENOIL": "transporte",
    "MARIA JOSE MAGALLANES CARBALLO": "alquileres, gastos casas y prestamo",
    "TELPARK": "transportes",
    "LIQUIDACION PERIODICA PRESTAMO": "alquileres, gastos casas y prestamo",
    "KIKO MILANO": "cosmetica",
    "SANTA LUCIA": "seguros",
    "ENDESA": "luz y gas",
    "CARREF": "alimentacion",
    "LEFTIES": "ropa",
    "MINISO LIFESTUL": "ropa",
    "PILAR GARCIA PEREZ CONCEPTO: ALQUILER": "alquileres, gastos casas y prestamo",
    "ORANGE ESPAGNE": "telefono",
    "STRADIVARIUS": "ropa",
    "YELMO CINES": "ocio",
    "CEDIPSA": "transporte",
    "COMPRA MM MADRID": "seguros",
    "TAGLIATELLA": "ocio",
    "NOMINA": "nomina",
    "HPI INSTANT INK": "informática y otros",
    "STEAM": "ocio",
    "SPOTIFY": "ocio",
    "MCAFEE": "informática y otros",
    "CANAL ISABEL II": "agua",
    "TELEPIZZA": "ocio",
    "E.S. ": "transporte",
    "FOSTER HOLLYWOOD": "ocio",
    "ALMIRANTE MARTELL": "alquileres, gastos casas y prestamo",
}